# Site
repository: AdvaithRavishankar/website
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Advaith Ravishankar
title: |
  Computer Vision Researcher @ Salk Institute 
  Math+CS and Cognitive Science (Spec. Machine Learning and Neural Computation) @ UC San Diego
email: advaith.ravishankar2002@gmail.com
# email_title: Email (Email title override)
phone: +1 858-8604276
# phone_title: Phone (Phone title override)

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  AdvaithRavishankar
linkedin_username: advaith-ravishankar-232b601b8

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profilepic.jpg
about_content: | # this will include new lines to allow paragraphs
  I am currently majoring in math and computer science at the University of California San Diego with a primary interest in Data Science.
  
  I enjoy conducting research experiments and have developed algorithms using Deep Learning and Regression. 
  
  My previous experiences include creating Robo-Advisory models, Convolutional and LSTM Neural Networks, Natural Language Processing, Clustering and Regression Algorithms applied to healthcare and finance.
  
  Currently open to any opportunity that helps me learn and grow in this field primarily in Reinforcement Learning, Natural Language Processing, Computer Vision, or Regression Algorithms.

content:
  - title: Focus & Expertise # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        #border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Deep Learning and Algorithms
        sub_title: Developer
        caption:
        link: 
        #additional_links:
        #  - title:  Github page for project (eg. sproogen/modern-resume-theme)
         #   icon: fab fa-github
        #    url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #  - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #    icon: fab fa-github
         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          I have a firm grasp over programming languages- Java, Python, R, SQL, JavaScript, and MATLAB- with the ability to use tools like TensorFlow, Pytorch, OpenCV, Bokeh, & Django.
          
          My expertise lies in the mathematical segment of these algorithm where I have specialization certifaction in and is also my current area of specialization at UCSD.
          
  - title: Organization Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        #border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Reinforcement Learning Based Poker Robot
        sub_title: Deep Learning Developer
        caption: Jan 2021 - Present
        link: https://github.com/packetsss/Poker-RL
        #additional_links:
        #  - title:  Github page for project (eg. sproogen/modern-resume-theme)
         #   icon: fab fa-github
        #    url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #  - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #    icon: fab fa-github
         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Creating an AI Poker robot based on a reinforcement learning model
        description: | # this will include new lines to allow paragraphs
          Designing custom reward functions and reinforcement learning models to play poker efficiently with the University of California San Diego Data Science Student Soceity	

  
  - title: Internship Experiences
    layout: list
    content:
      - layout: left
        title: Probe Information
        sub_title: Financial Research Intern
        caption: Jul 2021 - Aug 2021
        link: https://probeinformation.com/
        quote: >
          India's Leading Corporate Data Firm 
        description: | # this will include new lines to allow paragraphs
          Project objective was cluster 1.6 million companies to help banks identify companies for lending  
                Developed a smart search algorithm using biased clustering and an LSTM neural network
          	    Prototyped a backend website using Django to present interactive network graph and algorithm visualizations from bokeh

      - layout: left
        title: Scripbox
        sub_title: Financial Research Intern
        caption: Jun 2021 - Aug 2021
        link: https://scripbox.com/
        quote: >
          No.1 Robo-Advisory Platform Firm in India
        description: | # this will include new lines to allow paragraphs
          Goal to optimize investment portfolios by statistically analyzing indices and stocks
                Produced an application which would cluster all indices and stocks on a real-time basis on statistical measures
                Automatically ranked potential investments for return-on-investment optimization

      - layout: left
        title: Myelin Foundry
        sub_title: Deep Learning Intern
        caption: Jun 2020
        link: https://www.myelinfoundry.com/
        quote: >
          Artificial Intelligence Led Startup 
        description: | # this will include new lines to allow paragraphs
          Tasked to create a prediction algorithm to find the probability of a YouTube music video going viral
                Web scraped viral and non-viral music videos from YouTube
                Created a hybrid neural network to generate the probability of virality

      - layout: left
        title: Cerner
        sub_title: Data Science Intern
        caption: Jul 2018
        link: https://www.cerner.com/
        quote: >
          Leading Health and Information Technology Firm 
        description: | # this will include new lines to allow paragraphs
          Project aimed to correlate the incidence of malaria to local infrastructure and environmental conditions. Goal was to aid the government to reduce the spread of the disease in the country
                Designed logistical and linear regression algorithms to find regional hotspots of disease spread

          
  - title: Research Lab Experience
    layout: list
    content:
      - layout: left
        title: Swartz Center for Computational Neuroscience (SCCN),
        sub_title: Lab Volunteer
        caption: Oct 2021 - Present
        link: https://sccn.ucsd.edu/
        quote: >
          A UCSD Affiliated Lab which focuses on Electroencephalography (EEG) Analysis
        description: | # this will include new lines to allow paragraphs
          Project focused on developing a neural network to process Electroencephalography (EEG) data on adolescent brains for transferred learning
                Executing and debugging deep learning scripts on the Expanse Supercomputer
    
  - title: Education
    layout: list
    content:
      - layout: center
        title: University of California San Diego
        sub_title: BS Mathematics and Computer Science
        caption: 2021 - Present
        description: | # this will include new lines to allow paragraphs
          Pursuing a degree in Mathematics and Computer Science with an elective specialization in machine learning. Intend to complete in June 2025.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      IInterests: Reinforcement Learning, Natural Language Processing, Computer Vision, Regression Algorithms, Time Series
      
      Languages: Fluent in English & Hindi. Conversant in French
      
      Skills: Java, Python, R, SQL, JavaScript, and MATLAB
      
      Tools: TensorFlow, Pytorch, OpenCV, Bokeh, Django
      


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
