# Site
repository: AdvaithRavishankar/website
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Advaith Ravishankar
title: Computer Vision Researcher @ Salk Institute
email: advaith.ravishankar2002@gmail.com
# email_title: Email (Email title override)
phone: (858) 860 4276
# phone_title: Phone (Phone title override)

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  AdvaithRavishankar
linkedin_username: advaith-ravishankar-232b601b8

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profilepic.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a mathematics and computer science student specializing in Data Science and Artificial Intelligence. My current focus is on computer vision and its application with 2D pose estimation and categorical image identification. 

  I am well-versed with UNets, Data Clustering and Big Data Processing. Additionally, I am a skilled programmer in Python, Java, C, C++, R and ARM.

content: 
  - title: Education
    layout: list
    content:
      - layout: center
        title: University of California San Diego
        caption: 2021 - Present
        description: | # this will include new lines to allow paragraphs
          BS Mathematics and Computer Science 
          
          BS Cognitive Science Spec. Machine Learning and Neural Computation
          
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Computer Vision Researcher
        sub_title: Salk Institute
        caption: Apr 2022 - Present
        link: https://talmolab.org/team/
        quote: >
          Talmo Lab
        description: | # this will include new lines to allow paragraphs
          Creating a Self-Supervised Keypoint-Discovery addition to SLEAP.AI under Dr. Talmo Pereira using Heatmap styled jigsaw principle and BKinD.
      - layout: left
        title: Reinforcement Learning Poker Robot
        sub_title: Deep Learning Developer
        caption: Dec 2021 - Jun 2022
        link: https://github.com/AdvaithRavishankar/Poker.AI
        quote: >
          Data Science Student Soceity
        description: | # this will include new lines to allow paragraphs
          Created a Reinforcement Learning Based Poker Robot in collaboration with UCSD's Data Science Student Soceity. Created a functional model using Stable.Baseline3 and created a functional GUI which can be found in the Github Repository.   
    
      - layout: left
        title: Probe Information
        sub_title: Financial Research Intern
        caption: Jul 2021 - Aug 2021
        link: https://probeinformation.com/
        quote: >
          India's Leading Corporate Data Firm 
        description: | # this will include new lines to allow paragraphs
          Project objective was cluster 1.6 million companies to help banks identify companies for lending  
                Developed a smart search algorithm using biased clustering and an LSTM neural network
          	    Prototyped a backend website using Django to present interactive network graph and algorithm visualizations from bokeh

      - layout: left
        title: Scripbox
        sub_title: Financial Research Intern
        caption: Jun 2021 - Aug 2021
        link: https://scripbox.com/
        quote: >
          No.1 Robo-Advisory Platform Firm in India
        description: | # this will include new lines to allow paragraphs
          Goal to optimize investment portfolios by statistically analyzing indices and stocks
                Produced an application which would cluster all indices and stocks on a real-time basis on statistical measures
                Automatically ranked potential investments for return-on-investment optimization

      - layout: left
        title: Myelin Foundry
        sub_title: Deep Learning Intern
        caption: Jun 2020
        link: https://www.myelinfoundry.com/
        quote: >
          Artificial Intelligence Led Startup 
        description: | # this will include new lines to allow paragraphs
          Tasked to create a prediction algorithm to find the probability of a YouTube music video going viral
                Web scraped viral and non-viral music videos from YouTube
                Created a hybrid neural network to generate the probability of virality

      - layout: left
        title: Cerner Corporation
        sub_title: Data Science Intern
        caption: Jul 2018
        link: https://www.cerner.com/
        quote: >
          Leading Health and Information Technology Firm 
        description: | # this will include new lines to allow paragraphs
          Project aimed to correlate the incidence of malaria to local infrastructure and environmental conditions. Goal was to aid the government to reduce the spread of the disease in the country
                Designed logistical and linear regression algorithms to find regional hotspots of disease spread
  
  - title: Publications
    layout: list
    content:
      - layout: center
        title: Improving Nutrition in India
        sub_title: Pre-Print on NutriXiv
        caption: Oct 2020
        description: | # this will include new lines to allow paragraphs
          A short mathematical study analyzing the dietary nutrition of children living in destitute children care facilities in order to improve their diet distribution.
          
          Pre-Print Link: https://osf.io/preprints/nutrixiv/e4qpu
      


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
